<form class="custom">
    <div class="row">
        <div class="large-12 columns">
            <div class="row">
                <div class="large-12 columns"><h1>Регистрация партнера</h1></div>

                <div class="large-12 columns">
                    <input type="text" placeholder="Email">
                </div>

                <div class="large-12 columns">
                    <label>Выберите вид сотрудничества</label>
                    <select id="customDropdown1" class="medium">
                        <option></option>
                        <option>Магазин</option>
                        <option>Сайт / Мобильное приложение</option>
                    </select>
                </div>

                <div class="large-12 columns">
                    <a href="#" class="button">Отправить</a>
                </div>
            </div>
        </div>
    </div>
</form>