<?php foreach ($listing as $category) : ?>
    <h4><?= $category['category']['name'] ?></h4>
    <?php foreach ($category['product_list'] as $product) : ?>
        <div><?= $product['name'] ?></div>
        <div><?= $product['description'] ?></div>
        <div>
            <?= $product['price'] ?>
            <a href="/shop/newOrder/?product_list[]=<?= $product['id'] ?>&address=address&mobile=9841112233&name=test">купить</a>
        </div>
        <br />
    <?php endforeach; ?>
<?php endforeach; ?>