<!DOCTYPE html>
<!--[if IE 8]>
<html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en"> <!--<![endif]-->

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width"/>
    <title><?php echo Phalcon\Tag::getTitle(false) ?></title>

    <link rel="stylesheet" href="/css/normalize.css"/>

    <link rel="stylesheet" href="/css/foundation.css"/>


    <script src="/js/vendor/custom.modernizr.js"></script>
    <script src="/js/vendor/jquery.js"></script>

    <style>
        footer  {
            background-color: #fff;
            padding-top: 10px;
        }
    </style>

</head>
<body>

<nav class="top-bar">
    <ul class="title-area">
        <li class="name"><h1><a href="/one"><?php echo Phalcon\Tag::getTitle(false) ?></a></h1></li>
        <li class="toggle-topbar menu-icon"><a href="#"><span>Меню</span></a></li>
    </ul>

    <section class="top-bar-section">
        <ul class="left">
            <li class="divider"></li>
            <li><a href="/one/about">О нас</a></li>
            <li><a href="/one/about">Контакты</a></li>
        </ul>

        <?php echo $this->elements->getLogin() ?>
    </section>
</nav>

<?php echo $this->getContent(); ?>

<footer>
    <div class="row">
        <div class="large-12">Новая платформа продаж для магазинов</div>
    </div>
</footer>

<div id="loginModal" class="reveal-modal small">
    <h1>Авторизация</h1>

    <div class="block-login-fail hide">
        <div data-alert class="alert-box alert hide">
            Ошибка авторизации
            <a href="#" class="close">&times;</a>
        </div>
    </div>

    <form id="loginFrm">
        <div class="row">
            <div class="small-12">
                <input type="text" name="email" placeholder="Email">
            </div>
            <div class="small-12">
                <input type="password" name="password" placeholder="Пароль">
            </div>
            <div class="small-12">
                <a href="#" id="loginBtn" class="small button">Отправить</a>
            </div>
            <div><a href="/one/register">Регистрация</a></div>
        </div>
    </form>
    <a class="close-reveal-modal">&#215;</a>
</div>

<script>
    document.write('<script src=' +
        ('__proto__' in {} ? '/js/vendor/zepto' : '/js/vendor/jquery') +
        '.js><\/script>')
</script>

<script src="/js/foundation.min.js"></script>
<!--

<script src="/js/foundation/foundation.js"></script>

<script src="/js/foundation/foundation.alerts.js"></script>

<script src="/js/foundation/foundation.clearing.js"></script>

<script src="/js/foundation/foundation.cookie.js"></script>

<script src="/js/foundation/foundation.dropdown.js"></script>

<script src="/js/foundation/foundation.forms.js"></script>

<script src="/js/foundation/foundation.joyride.js"></script>

<script src="/js/foundation/foundation.magellan.js"></script>

<script src="/js/foundation/foundation.orbit.js"></script>

<script src="/js/foundation/foundation.placeholder.js"></script>

<script src="/js/foundation/foundation.reveal.js"></script>

<script src="/js/foundation/foundation.section.js"></script>

<script src="/js/foundation/foundation.tooltips.js"></script>

<script src="/js/foundation/foundation.topbar.js"></script>

-->

<script>
    $(document).foundation();
</script>

<script>
    $(function () {
        $("#loginBtn").click(function (event) {
            $.post("/one/auth", $("#loginFrm").serialize(), function (data) {
                if (data.status == 'success') {
                    $(location).attr('href',data.redirect);
                } else {
                    $(".block-login-fail").show();
                }
            }, 'json');
            return false;
        })
    });
</script>

</body>
</html>